import { adviseTextLayout, adviseFocusVisible, adviseFormErrors, adviseComponent } from '../services/adviceEngine.js';
import { adviseColourContrast, checkCssRule } from '../services/ruleEngine.js';
export const accessibility_advise_text_layout={name:'accessibility_advise_text_layout',description:'Advise on source-backed text layout and paragraph formatting rules.',inputSchema:{type:'object',properties:{question:{type:'string'},target_level:{type:'string'},context:{type:'string'}},required:['question']},handler:adviseTextLayout};
export const accessibility_advise_colour_contrast={name:'accessibility_advise_colour_contrast',description:'Calculate contrast and return WCAG-backed colour guidance.',inputSchema:{type:'object',properties:{foreground:{type:'string'},background:{type:'string'},text_size:{type:'string'},target_level:{type:'string'}},required:['foreground','background']},handler:adviseColourContrast};
export const accessibility_advise_focus_visible={name:'accessibility_advise_focus_visible',description:'Advise on keyboard focus indicators and WCAG focus requirements.',inputSchema:{type:'object',properties:{target_level:{type:'string'},context:{type:'string'}}},handler:adviseFocusVisible};
export const accessibility_advise_form_errors={name:'accessibility_advise_form_errors',description:'Advise on form errors, labels, instructions, and suggestions.',inputSchema:{type:'object',properties:{target_level:{type:'string'},context:{type:'string'}}},handler:adviseFormErrors};
export const accessibility_advise_component={name:'accessibility_advise_component',description:'Advise on an accessibility component pattern.',inputSchema:{type:'object',properties:{component:{type:'string'},target_level:{type:'string'},context:{type:'string'}},required:['component']},handler:adviseComponent};
export const accessibility_check_css_rule={name:'accessibility_check_css_rule',description:'Run deterministic WCAG-related CSS/design rule checks.',inputSchema:{type:'object',properties:{css:{type:'string'},target_level:{type:'string'},context:{type:'string'}},required:['css']},handler:checkCssRule};
export const accessibility_get_component_requirements={name:'accessibility_get_component_requirements',description:'Get component requirements for build agents.',inputSchema:{type:'object',properties:{component:{type:'string'},target_level:{type:'string'},include:{type:'array',items:{type:'string'}}},required:['component']},handler:adviseComponent};
